### ISSUE TITLE
Unwanted comma

### ISSUE THREAD

**Issue by LiveNL** [bronzehedwick/Adobe-Export-Scripts#2]
https://github.com/bronzehedwick/Adobe-Export-Scripts/blob/865e1c362621d054f57b4ef18a1a7fb5b23c13d2/Illustrator/Export%20Layout.jsx#L112

The comma at the end of this line is causing problems (non-valid json).

**Comment by bronzehedwick** [comment]
Thanks for reporting the issue! I'd be happy to accept a pull request on this ;)

**Comment by LiveNL** [comment]
Somehow I couldn't reproduce this anymore. Let's close this until I stumble upon it again :)
